services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=urlshortener'
      - 'MYSQL_PASSWORD=secret247'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
