

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/urlshortener
    username: mysuer
    password: secret247

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL8Dialect

  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


server:
  port: 8888

logging:
  level:
    org.springframework: INFO
    com.niyiment.urlshortener: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics"