name: CI/CD for Java Backend and React Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for Java backend
  build-and-test-backend:
    runs-on: ubuntu-latest
    defaults:
      runs: 
        working-directory: ./

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup JDK 21
        uses: actions/checkout@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build backend with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx (for backend image)
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (for backend image)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ # Context is the backend directory
          file: ./Dockerfile # Path to backend Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest        
